language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
script:
  - bundle exec rspec
  - bundle exec cucumber

branches:
  only:
    - master

notifications:
  email:
    - jwaterfaucett@gmail.com
